"""
Moteur de templates basé sur Jinja2 pour Wara9a.

Gère le rendu des templates avec des filtres personnalisés
et un système de templates intégrés.
"""

import logging
from pathlib import Path
from typing import Dict, Any, List, Optional
from datetime import datetime, timedelta

import jinja2
from jinja2 import Environment, FileSystemLoader, BaseLoader, TemplateNotFound

from wara9a.core.config import TemplateConfig


logger = logging.getLogger(__name__)


class BuiltinTemplateLoader(BaseLoader):
    """Loader pour les templates intégrés de Wara9a."""
    
    def __init__(self):
        # Templates intégrés (sera étendu plus tard)
        self.templates = {
            "readme": self._readme_template(),
            "changelog": self._changelog_template(),
            "release_notes": self._release_notes_template(),
        }
    
    def get_source(self, environment: Environment, template: str):
        if template not in self.templates:
            raise TemplateNotFound(template)
        
        source = self.templates[template]
        return source, None, lambda: True
    
    def list_templates(self) -> List[str]:
        return list(self.templates.keys())
    
    def _readme_template(self) -> str:
        return """# {{ project.name }}

{% if project.description %}
{{ project.description }}
{% endif %}

{% if data.repository.description and data.repository.description != project.description %}
{{ data.repository.description }}
{% endif %}

## 📊 Statistiques du projet

- **Commits récents**: {{ data.commits | length }}
- **Issues ouvertes**: {{ open_issues | length }}
{% if latest_release %}
- **Dernière version**: [{{ latest_release.tag }}]({{ latest_release.url }}) ({{ latest_release.created_at | format_date }})
{% endif %}
- **Langage principal**: {{ data.repository.languages | first | default("Non détecté") }}

{% if data.repository.topics %}
## 🏷️ Topics
{{ data.repository.topics | join(", ") }}
{% endif %}

{% if recent_commits %}
## 📝 Commits récents

{% for commit in recent_commits %}
- **{{ commit.date | format_date }}** - {{ commit.message | truncate(80) }} ([{{ commit.sha[:7] }}]({{ commit.url }}))
{% endfor %}
{% endif %}

{% if open_issues %}
## 🐛 Issues ouvertes

{% for issue in open_issues[:5] %}
- [{{ issue.title }}]({{ issue.url }}) - {{ issue.created_at | format_date }}
{% endfor %}

{% if open_issues | length > 5 %}
... et {{ open_issues | length - 5 }} autres issues
{% endif %}
{% endif %}

---

*Documentation automatically generated by [Wara9a](https://github.com/elhajjaji/wara9a) on {{ now() | format_datetime }}*
"""
    
    def _changelog_template(self) -> str:
        return """# Changelog

Toutes les modifications notables de ce projet sont documentées dans ce fichier.

{% for release in data.releases | sort(attribute='created_at', reverse=true) %}
## [{{ release.tag }}] - {{ release.created_at | format_date }}

{% if release.description %}
{{ release.description }}
{% endif %}

{% set release_commits = data.commits | select_since_release(release) %}
{% if release_commits %}
### Commits inclus

{% for commit in release_commits %}
- {{ commit.message | truncate(80) }} ([{{ commit.sha[:7] }}]({{ commit.url }}))
{% endfor %}
{% endif %}

{% endfor %}

---

*Changelog automatically generated by [Wara9a](https://github.com/elhajjaji/wara9a)*
"""
    
    def _release_notes_template(self) -> str:
        return """# Notes de version {{ latest_release.tag if latest_release else project.version }}

{% if latest_release %}
**Date de sortie**: {{ latest_release.created_at | format_date }}

{% if latest_release.description %}
## Description

{{ latest_release.description }}
{% endif %}

{% set release_commits = data.commits | select_since_previous_release(latest_release) %}
{% if release_commits %}
## Modifications incluses

{% set features = release_commits | select('message', 'match', '^feat') %}
{% set fixes = release_commits | select('message', 'match', '^fix') %}
{% set others = release_commits | reject('message', 'match', '^(feat|fix)') %}

{% if features %}
### ✨ Nouvelles fonctionnalités

{% for commit in features %}
- {{ commit.message | clean_commit_message }} ([{{ commit.sha[:7] }}]({{ commit.url }}))
{% endfor %}
{% endif %}

{% if fixes %}
### 🐛 Corrections de bugs

{% for commit in fixes %}
- {{ commit.message | clean_commit_message }} ([{{ commit.sha[:7] }}]({{ commit.url }}))
{% endfor %}
{% endif %}

{% if others %}
### 🔧 Autres modifications

{% for commit in others %}
- {{ commit.message | clean_commit_message }} ([{{ commit.sha[:7] }}]({{ commit.url }}))
{% endfor %}
{% endif %}

## Statistiques

- **{{ release_commits | length }}** commits inclus
- **{{ release_commits | sum(attribute='additions') }}** lignes ajoutées
- **{{ release_commits | sum(attribute='deletions') }}** lignes supprimées
- **{{ release_commits | map(attribute='files_changed') | sum | length }}** fichiers modifiés
{% endif %}

{% else %}
*Aucune release trouvée*
{% endif %}

---

*Release notes automatically generated by [Wara9a](https://github.com/elhajjaji/wara9a)*
"""


class TemplateEngine:
    """
    Moteur de rendu des templates pour Wara9a.
    
    Utilise Jinja2 avec des filtres personnalisés et un système
    de templates intégrés + templates utilisateur personnalisés.
    """
    
    def __init__(self, template_dirs: Optional[List[Path]] = None):
        """
        Initialise le moteur de templates.
        
        Args:
            template_dirs: Dossiers contenant les templates personnalisés
        """
        self.template_dirs = template_dirs or []
        
        # Configurer Jinja2 avec loaders multiples
        loaders = [BuiltinTemplateLoader()]
        
        # Ajouter les dossiers de templates personnalisés
        for template_dir in self.template_dirs:
            if template_dir.exists():
                loaders.append(FileSystemLoader(str(template_dir)))
        
        # Loader combiné (cherche dans l'ordre: personnalisé puis intégré)
        loader = jinja2.ChoiceLoader(loaders[::-1])  # Inverser pour prioriser les personnalisés
        
        self.env = Environment(
            loader=loader,
            autoescape=False,  # Pas d'échappement HTML par défaut
            trim_blocks=True,
            lstrip_blocks=True,
            keep_trailing_newline=True,
        )
        
        # Ajouter les filtres personnalisés
        self._register_filters()
        
        # Ajouter les fonctions globales
        self._register_globals()
    
    def render(self, template_name: str, context: Dict[str, Any], 
              template_config: Optional[TemplateConfig] = None) -> str:
        """
        Rend un template avec le contexte donné.
        
        Args:
            template_name: Nom du template à rendre
            context: Variables à passer au template
            template_config: Configuration du template (optionnel)
            
        Returns:
            Contenu rendu du template
            
        Raises:
            TemplateNotFound: Si le template n'existe pas
            TemplateError: Si erreur lors du rendu
        """
        try:
            # Utiliser un template personnalisé si spécifié
            if template_config and template_config.template_file:
                template_path = Path(template_config.template_file)
                if template_path.is_absolute() and template_path.exists():
                    # Charger directement le fichier
                    template_content = template_path.read_text(encoding='utf-8')
                    template = self.env.from_string(template_content)
                else:
                    # Chercher dans les dossiers de templates
                    template = self.env.get_template(template_config.template_file)
            else:
                # Utiliser le template intégré
                template = self.env.get_template(template_name)
            
            # Rendre le template
            rendered = template.render(**context)
            
            logger.debug(f"Template {template_name} rendu avec succès")
            return rendered
            
        except TemplateNotFound as e:
            logger.error(f"Template non trouvé: {e}")
            raise
        except Exception as e:
            logger.error(f"Erreur lors du rendu du template {template_name}: {e}")
            raise
    
    def has_template(self, template_name: str) -> bool:
        """Vérifie si un template existe."""
        try:
            self.env.get_template(template_name)
            return True
        except TemplateNotFound:
            return False
    
    def list_builtin_templates(self) -> List[str]:
        """Retourne la liste des templates intégrés."""
        builtin_loader = BuiltinTemplateLoader()
        return builtin_loader.list_templates()
    
    def _register_filters(self) -> None:
        """Enregistre les filtres Jinja2 personnalisés."""
        
        def format_date(date: datetime, format_str: str = "%d/%m/%Y") -> str:
            """Formate une date."""
            if not date:
                return "Date inconnue"
            return date.strftime(format_str)
        
        def format_datetime(date: datetime, format_str: str = "%d/%m/%Y %H:%M") -> str:
            """Formate une date avec heure."""
            if not date:
                return "Date inconnue"
            return date.strftime(format_str)
        
        def time_ago(date: datetime) -> str:
            """Retourne le temps écoulé depuis une date."""
            if not date:
                return "Date inconnue"
            
            now = datetime.now(date.tzinfo) if date.tzinfo else datetime.now()
            delta = now - date
            
            if delta.days > 0:
                return f"il y a {delta.days} jour{'s' if delta.days > 1 else ''}"
            elif delta.seconds > 3600:
                hours = delta.seconds // 3600
                return f"il y a {hours} heure{'s' if hours > 1 else ''}"
            elif delta.seconds > 60:
                minutes = delta.seconds // 60
                return f"il y a {minutes} minute{'s' if minutes > 1 else ''}"
            else:
                return "à l'instant"
        
        def clean_commit_message(message: str) -> str:
            """Nettoie un message de commit."""
            # Supprimer les préfixes conventionnels
            message = message.replace('feat:', '').replace('fix:', '').replace('docs:', '')
            message = message.replace('style:', '').replace('refactor:', '').replace('test:', '')
            return message.strip()
        
        def truncate(text: str, length: int = 50, end: str = "...") -> str:
            """Tronque un texte."""
            if not text or len(text) <= length:
                return text or ""
            return text[:length - len(end)] + end
        
        def select_since_release(commits: List[Dict], release: Dict) -> List[Dict]:
            """Sélectionne les commits depuis une release."""
            if not release or not commits:
                return []
            
            release_date = release.get('created_at')
            if not release_date:
                return commits
                
            return [c for c in commits if c.get('date', datetime.min) >= release_date]
        
        def select_since_previous_release(commits: List[Dict], current_release: Dict) -> List[Dict]:
            """Sélectionne les commits depuis la release précédente."""
            # Pour l'instant, retourne tous les commits de la dernière semaine
            if not commits:
                return []
                
            week_ago = datetime.now() - timedelta(days=7)
            return [c for c in commits if c.get('date', datetime.min) >= week_ago]
        
        # Enregistrer les filtres
        self.env.filters['format_date'] = format_date
        self.env.filters['format_datetime'] = format_datetime
        self.env.filters['time_ago'] = time_ago
        self.env.filters['clean_commit_message'] = clean_commit_message
        self.env.filters['truncate'] = truncate
        self.env.filters['select_since_release'] = select_since_release
        self.env.filters['select_since_previous_release'] = select_since_previous_release
    
    def _register_globals(self) -> None:
        """Enregistre les fonctions globales."""
        
        def now() -> datetime:
            """Retourne la date/heure actuelle."""
            return datetime.now()
        
        # Enregistrer les globales
        self.env.globals['now'] = now